name: ${project.name}
main: com.wyvencraft.death.WyvenDeathPlugin
description: A custom death experience plugin.
version: ${project.version}
author: WyvenCraft
api-version: '1.21'
load: POSTWORLD
commands:
  kill:
    description: Kill a player.
    usage: /kill <player>
    aliases:
      - suicide